### PR TITLE
Add support for KiCAD 7 when setting precision

### PR DESCRIPTION
**Pull request by ALEEF02**
The attribute `aUseInch` was removed about 2 years ago: https://github.com/KiCad/kicad-source-mirror/commit/5b8eb8f9ec6e45e45d4617928cc067fbf77a922e

Tested on Ubuntu 22.04.

### CODE REVIEW

**Comment by ALEEF02** [comment]
It seems this has been implemented in part in @leoheck's fork, but is still unmerged. Merging this will cause a merge conflict with his branch.

**Comment by Gasman2014** [comment]
Sorry I haven’t been doing a lot with this project recently as I had plans to completely rewrite using the kicad-cli tools but have not managed to carve out sufficient time. Thank you for the MR - I think Leo Heck has been a bit more active recently and might take a look.

John

**Comment by leoheck** [comment]
@ALEEF02 If my fork is good for you, you should use it instead. 
If you install Kiri, it will install fork instead since it gives extra command line features required for Kiri.
I could make a PR with my fork here, but I stopped using and maintaining this repo since Fossil and SVN are kind of hard to test especially for SVN that requires a server.

**Comment by leoheck** [comment]
@Gasman2014 please, don't change this to use kicad-cli, it will not be good. The `plot-pcb` script is way faster. Kicad-cli sucks for plotting `pbc-layers`. It is good if you plot schematics. I think I have a flag on my fork of kicad-diff to plot using kicad-cli. At least I added a flag to plot schematics which uses kicad-cli.

**Comment by Gasman2014** [comment]
Hi Leandro,

I was thinking that kicad-cli would be a _much_ simpler option for the schematics and, for consistency and code simplification, might be OK for the PCB too. I have not done any speed testing so was aware that there might be some speed hit but wasn’t sure how significant it would be.  Will bear this in mind and try it out before making any further plans that way!

Best Wishes

John

**Comment by leoheck** [comment]
For schematic it is awesome. For layout, it wont change anything since pcb_plot is better.

**Comment by Gasman2014** [comment]
One of the features of KiCad-cli that caught my eye was —page-size-modeSetting this to 2 does a nice trim to the board features which seems consistent. It may be worth exploring as a way of focusing on the active area for the diff. I don’t think plot_pcb is quite so useful for that aspect but I agree speed is key! JohnSent from my iPadOn 2 Jul 2024, at 19:35, Leandro Heck ***@***.***> wrote:﻿
For schematic it is awesome. For layout, it wont change anything since pcb_plot is better.

**Comment by leoheck** [comment]
I updated my fork fixing the schematics plot. @ALEEF02 @Gasman2014 

You can enable this by passing the `.kicad_pro` which will plot both schematics and layout. Or if you pass the `.kicad_sch` it will plot the schematics only. Alternatively, passing `.kicad_pcb` as usual will plot PCB layers only.

However, there is a new flag (`-x`) for overriding the same settings. 
The default value is `ext` which means it follows the extension of the given file. 
`all` will plot both schematics and layers and `sch`|`pcb` will plot the schematics or layers respectively. 

@Gasman2014  There is also another flag `-c` to plot PCB layers using `kicad-cli`. Each layer has to be generated individually as far as I know, so this takes time since it has to run the kicad-cli for each layer and also for each of the 2 boards.

Here is an example using this command:
```bash
# It was given the kicad_pro file
➜ kidiff -r -k board.kicad_pro -c -f
Exporting schematics and layouts

      SCM Selected: git 
   Kicad File Path: /home/lheck/Dropbox/Documents4/KICAD_PROJECTS/assoc-board/board.kicad_pro
Kicad Project Path: /home/lheck/Dropbox/Documents4/KICAD_PROJECTS/assoc-board
         REPO Path: /home/lheck/Dropbox/Documents4/KICAD_PROJECTS/assoc-board
 Kicad Project Dir: .
   Board File Name: board.kicad_pro
        Output Dir: /home/lheck/Dropbox/Documents4/KICAD_PROJECTS/assoc-board/.kidiff

Commit 1 (a): local
Commit 2 (b): a7bb19c | 2024-04-02 15:07:25 | Leandro Heck | Update to Kicad 8

Ploting pcb layers with kicad-cli, this takes time...

Starting webserver at http://127.0.0.1:9092/web/index.html
(Hit Ctrl+C to exit)

```

image

**Comment by ALEEF02** [comment]
Looks like @leoheck is making good progress and my change here is unnecessary. Just because I'm lazy, I'm still using my small change to have the program run ;)

**Pull request closed without merging**
