### PR TITLE
[WIP] Fix some issues from the last PR

### PR DESCRIPTION
**Pull request by leoheck**
The code was pushed, but it was not completely finished/reviewed. I am opening this PR to finish this.
- Git was working after this PR.
- Fossil still working
- SVN is being fixed

### CODE REVIEW

**Comment by leoheck** [comment]
Hey @Gasman2014 now it looks good. 
I tested with these 3 SCM. I am not sure it is working with multiples directories yet.
This branch has also no conflicts with your master.
I think this is a good PR to merge now.

**Comment by Gasman2014** [comment]
Thank you. Shouldn't have pulled the trigger so soon. Will need to spin up a new SVN to check that function but I will merge this straight away.

**Comment by Gasman2014** [comment]
I have just found a problem with this. The path for the generated .svg images should be in

`kidiff/[VERSON]/[BOARDNAME].svg`

however, the images are now being generated in an '-o' subfolder.

`kidiff/[VERSION]/-o/[BOARDNAME].svg`

When testing, I failed to remove the 'kidiff' directory and only ran it on a repo where I had already generated a diff, hence the display logic picked up the old .svg files.

**Comment by Gasman2014** [comment]
I have managed to fix this in my master and it seems to work for Fossil. I've added in some print logging. I haven't had time to check if it is OK for Git / SVN.

Could you check it out and perhaps rebase any further changes from my master branch?

**Comment by leoheck** [comment]
Cool, I will check against the other SCMs later. The issue may be related to the fact that git version was planed to support multiples (maybe nested) projects. But the others have still the same old behavior. I want to check this, I just have to create some sample projects for this with this architecture too.

**Pull request merged**
