### PR TITLE
Improve layers and the way they are handled using the ID instead of the file name

### PR DESCRIPTION
**Pull request by leoheck**
This PR updates `plotpcb` to use layer IDs instead of layer names. Also, only used layers are being generated which simplifies the review without useless layers. 

Extra improvements
- Improve layer order, they are now the same as they appear in Kicad since it is using layer ID to sort them
- `plotpcb` has a flag to print layers `-l`
- Improve layer colors and add extra layers (it also color layers when they have custom names)
- Fix version, date background color that was missing, now they are in green/red like other fields (see following images)
- Normalize python code with [black python formatter](https://pypi.org/project/black/)
- Minor change: variable normalization updating some UPPERCASE and CammelCase words to snake_case making it more readable (this is was not exhaustive yet)
- Minor style updates removing high contrast with white.
- Minor updates in README.md too

Show board layers using `plotpcb`

```
➜ plotpcb HHKB_controller.kicad_pcb -l
 # ID Name
 1  0 F.Cu
 2  1 In1.Cu
 3  2 In2.Cu
 4 31 B.Cu
 5 34 B.Paste
 6 35 F.Paste
 7 36 B.SilkS
 8 37 F.SilkS
 9 38 B.Mask
10 39 F.Mask
11 40 Dwgs.User
12 41 Cmts.User
13 44 Edge.Cuts
14 45 Margin
15 46 B.CrtYd
16 47 F.CrtYd
```

This project has 4 copper layers
image

The project has 2 copper layers, for instance
image

When the user changes the project, reducing or increasing the number of the board's layers, some `blank.svg` files are generated to create a clean comparison. Check the following image.

image

Here the white borders were replaced with this gray
image

Here the initial grid was white or high contrast, now it is inverted, the selection is more white.
image

### CODE REVIEW

**Comment by leoheck** [comment]
Since this is a big PR I am not merging this automatically since it is the first time after you gave access to this repo and I am not sure how do you prefer to work. Let me know if it is ok for me to merge things directly next time.

**Comment by leoheck** [comment]
This is the layer view on Safari now. Not perfect but it is better than black.
Screen Shot 2021-07-02 at 00 19 09

**Comment by Gasman2014** [comment]
Thanks for this - and I like the bug fixes and changes. Limiting the layer output to valid layers was on something I was planning to do. Happy with the proposed layer colours recycling from 8 and the stylistic improvements.

I am hitting a problem with this though

```
EDA_Workspace/Projects/Test_SCM_Projects/trial_git/kidiff/./789491b']
Traceback (most recent call last):
  File "./kidiff", line 827, in <module>
    make_support_files(board_file, kicad_project, prjct_path, svg_dir1, svg_dir2)
  File "./kidiff", line 218, in make_support_files
    layer_id = int(file_name.replace(project_name + "-", "")[0:2])
ValueError: invalid literal for int() with base 10: 'B_'
```
Which is coming from
```
+ layer_id = int(file_name.replace(project_name + "-", "")[0:2])
Changes   a7e8114  ⟷   db7dc27   |   
```

I'm definitely running the latest version of plotpcb.

```which plotpcb
/Users/johnpateman/Documents/Code/KiCad-Diff/plotpcb
```
 which is picking up the layer info.
```
./plotpcb /Users/johnpateman/EDA_Workspace/Projects/MilliVolt2/MilliVolt2.kicad_pcb -l
(' #', 'ID', 'Name')
 1  0 Top
 2  1 In1.Cu
 3  2 In2.Cu
 4 31 Bottom
 5 32 B.Adhes
 6 33 F.Adhes 
```

**Comment by Gasman2014** [comment]
My bad. Never mind, I just removed the pre-existing kidiff directory and it works.

**Comment by Gasman2014** [comment]
In Firefox, your css changes work - i.e. the two pane view at the bottom is correctly coloured but this doesn't work for me  in Safari.

The class providing the colour info (i.e in this case In1_Cu) needs to be within the 'svg-img1-id' id tag (as shown below) and **not** in the 'image_1' tag as it is at present. With this change, the page works in both Safari and Firefox. 

Validating the HTML does show a few problems which might benefit from a tidy up - mostly style definitions which are unnecessary and overwritten by the CSS but there are a few <th><td> tag problems which might be worth looking at.

If this is fixed then I'll merge. :)


```
        <div id="image1-container" style="border: 1px solid #555; width: 50%; height: 250px">
            <div style="width: 100%; height: 250px">
                <svg id="svg-img1-id" xmlns="http://www.w3.org/2000/svg"
                    style="display: inline; width: 100%; min-width: 100%; max-width: 100%; height: 100%; min-height: 100%; max-height: 100%;"
                    version="1.1" class="In1_Cu">
                    <svg id="image_1">
                        <image x="0" y="0" height="100%" width="100%" xlink:href="../../e89f30/MilliVolt2-01-In1_Cu.svg" />
                    </svg>
                </svg>
            </div>
        </div>
```

**Comment by leoheck** [comment]
Yes, it is necessary to remove previous files that do not follow the format from the folder to avoid this issue. I will check if I can harden this problem. I think it is possible, it is just a matter of selection files with that format instead of iterating on all .svg files found there. Let me give it a try.

Regarding css changes on Safari. Which version do you have? I tested it on Safari it was showing fine. Safari is a total different world. Let me test your proposal to see how it behaves here.

**Comment by leoheck** [comment]
> Thanks for this - and I like the bug fixes and changes. Limiting the layer output to valid layers was on something I was planning to do...

Yeap. I knew it. You may have comented about it somewhere in an issue sometime ago. I also felt that I was always reviewing more layers than necessary haha.

**Comment by leoheck** [comment]
> Happy with the proposed layer colors recycling from 8 and the stylistic improvements.

Oh, I came with an improved way now. Instead of fallback to a fixed `In8.cu`. I changed it to reuse the colors from `In1.cu` to `In8.cu` in a cyclic way.

**Comment by leoheck** [comment]
Hey @Gasman2014 I could not resist, I have implemented the possibility to change pages using the keyboard. 
So, if you want to test it. Go inside the triptych view. And navigate using the arrows left, right or h/H to go home.

**Comment by Gasman2014** [comment]
I've been travelling today so haven't had a chance to look at the latest changes but they look good. Knew you couldn't resist adding keyboard controls - it's an excellent idea!

**Comment by leoheck** [comment]
This is something I had mention before in an issue, but it happens that it was basically copying something that I have learned doing kdiff so it was easy. I mentioned it here because I haven't put this info anywhere. Let see how you will feel using it.

**Comment by Gasman2014** [comment]
With the changes introduced in  fc0de47  ⟷   b9b4fa8 Im getting os.path errors.

   ```
 if not os.path.exists(args.kicad_pcb):
        print("Kicad file {} does not exit".format(args.kicad_pcb))
        exit(1)

    _, extension = os.path.splitext(args.kicad_pcb)
    if extension != ".kicad_pcb":
        print("The file {} seems not to be a Kicad PCB".format(args.kicad_pcb))
        exit(1)

```

  ```
File "./kidiff", line 774, in <module>
    if not os.path.exists(args.kicad_pcb):
  File "/Users/johnpateman/opt/miniconda3/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by Gasman2014** [comment]
So the changes you proposed in the section work fine when the tool is launched from the command line but if you just launch  a GUI interface then I run into the issues above. These checks are not necessary if you select a kicad_pcb file from the system file selector - there is already a 'kicad_pcb' filter set in the gui so only appropriate files can be selected -they are really only necessary when you are launching the full spec from the command line. I would suggest that this section is simply indented so it only applies when the CLI incantation is used.

ie. FROM

```
if __name__ == "__main__":

    signal.signal(signal.SIGINT, signal_handler)
    args = parse_cli_args()

    if args.kicad_pcb is None:
        kicad_project_path, board_file = select_project_gui(args.display)
    else:
        kicad_project_path = os.path.dirname(os.path.realpath(args.kicad_pcb))
        board_file = os.path.basename(os.path.realpath(args.kicad_pcb))

    if not os.path.exists(args.kicad_pcb):
        print("Kicad file {} does not exit".format(args.kicad_pcb))
        exit(1)

    _, extension = os.path.splitext(args.kicad_pcb)
    if extension != ".kicad_pcb":
        print("The file {} seems not to be a Kicad PCB".format(args.kicad_pcb))
        exit(1)
```

TO
```
if __name__ == "__main__":

    signal.signal(signal.SIGINT, signal_handler)
    args = parse_cli_args()

    if args.kicad_pcb is None:
        kicad_project_path, board_file = select_project_gui(args.display)
    else:
        kicad_project_path = os.path.dirname(os.path.realpath(args.kicad_pcb))
        board_file = os.path.basename(os.path.realpath(args.kicad_pcb))

        if not os.path.exists(args.kicad_pcb):
            print("Kicad file {} does not exit".format(args.kicad_pcb))
            exit(1)

        _, extension = os.path.splitext(args.kicad_pcb)
        if extension != ".kicad_pcb":
            print("The file {} seems not to be a Kicad PCB".format(args.kicad_pcb))
            exit(1)
```

**Comment by Gasman2014** [comment]
Nice one! Your fix makes better sense. Thanks for that.

**Comment by leoheck** [comment]
I was using your suggestion hehe. Cool.

**Pull request closed without merging**
