### PR TITLE
exit if no difference

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**
This is my attempt at fixing #95
I don't know Python, so I don't know if this is the correct way to fix this, but it does seem to work in my scenario.

### CODE REVIEW

**Comment by Gasman2014** [comment]
Thanks for looking at this and the MR. However, I don’t think the program should bail out at this point.

Whilst it is important to identify on the CL that there is no difference between commits, the diff strategy *does* need to create artefacts at all commit points. There is a difference between a CI workflow where you can bail out when no differences are detected and the full web interface where we need to generate svgs at each point in order to have something to compare between commits. i.e if we have three commits a -> b -> c and commit a and b are the same, we still have to generate ‘b’ as the web interface needs a point of reference for a b/c comparison.

Probably the best way to do this would be a command line switch for ‘abandon if no differences found’.

**Comment by chuckwagoncomputing** [comment]
OK I think I understand. I will close this, and PR a removal of the return statements in git.py.

**Comment by leoheck** [comment]
From your issue

> 
Also, it only gives the error when there weren't any changes between the two commits. If there were changes, a diff is produced without error.

@chuckwagoncomputing I would like to do something about the behavior you are describing. I don't like the current behavior either. I was thinking that we could have a command line flag that exits fine without an error if there are no changes. I would like to see the diff even if the files don't have changes. I am going to implement this in my branch. I just did not have time for this yet. But I will let you know once I do it.

**Comment by leoheck** [comment]
@chuckwagoncomputing, I could improve my main repo with this behavior. 

Could you check if it works for you? 

You should use the command line flag `-k` or `--keep-going` to continue plotting if the PCBs have no differences. Hope this works for you. This will present the page with the layers. It is a good way to just review the layers. 

Alternatively, if the boards do not have changes, then the program exits nicelly as it is supposed to do (this was fixed too)

**Comment by chuckwagoncomputing** [comment]
Seems to have done the trick; thank you!

**Comment by leoheck** [comment]
Good, I will make the PR here.

**Pull request closed without merging**
