### PR TITLE
Style and syntax

### PR DESCRIPTION
**Pull request by jnavila**
This part contains changes which are deeper and would require cross checks.

Thank you.

### CODE REVIEW

**Comment by jnavila** [comment]
Hello, this is all for now.  I tested on some projects I cloned from github, and it seems to work correctly for git. 

I have no source for svn or fossil. If anyone can cross-check with them, and tell if I broke anything, that would be great.

What's still missing before a great pause, is getting rid of the external call to plotpcb. I don't understand the reason behind this chain of call. Why need to do python->shell script -> python, with only minimal value in the script? I must be missing something.

**Comment by Gasman2014** [comment]
Thanks, Jean-Nöel. I will have a look and see if I can merge that. Thank you very much for the work that you have done. It is looking a whole lot more professional now. 
When I started this, I had lots of problems with python on macOS - the pcbnew version is 2.7 and you couldn't import pcbnew into a system python nor pip install anything into the KiCad version. I haven't tried recently but we are still on 2.7 in the current 5.99 nightlies.

**Comment by Gasman2014** [comment]
OK, hitting a problem with Fossil. Can select the artefacts but borking on 

```
 SCM Selected: fossil
  Project PATH: /Users/johnpateman/EDA_Workspace/Projects/JW_Avalanche/
 Kicad Project: .
    Board Name: Avalanche.kicad_pcb

Getting artifacts
['fossil', 'finfo', '-b', 'Avalanche.kicad_pcb']

 Commit 1 (a): 183f648923 | 2021-02-15 | johnpate |  |   trunk Minor adjustments to RefDes markers on
 Commit 2 (b): d4c7716931 | 2021-02-10 | johnpate |  |   trunk Adjusted size of zones

Getting Boards
['fossil', 'diff', '--brief', '-r', '183f64', '--to ', 'd4c771']

There is no difference in .kicad_pcb file in selected commits
```

However, there is a true difference as the output of the Fossil diff command is valid;

```
fossil diff --brief -r 183f64 --to d4c771
CHANGED Avalanche.kicad_pcb
```

**Comment by jnavila** [comment]
Thank you for your feedback. I finally converted a Git project to Fossil and ran kidiff on it. It turns out I forgot some spaces in the arguments while converting from command line to list of args. My last push should work for fossil.

**Comment by jnavila** [comment]
> When I started this, I had lots of problems with python on macOS - the pcbnew version is 2.7 and you couldn't import pcbnew into a system python nor pip install anything into the KiCad version. I haven't tried recently but we are still on 2.7 in the current 5.99 nightlies.

Ah, that's a Python version issue... I knew I had missed something big :smile: But it seems thatpcbnew binding are for Python3 now:

https://github.com/Gasman2014/KiCad-Diff/blob/335a151e30bc9cc51e6b8d3710887feb5836baf2/plotpcb#L44

So shortcutting this should work and simplify usage.

**Comment by jnavila** [comment]
The missing fields were not present in Git, but I added them. Note that Git does not record branch names in the commits.

**Comment by Gasman2014** [comment]
Thanks for all your help with this. Glad to get it merged and make further progress with this tool.

**Comment by jnavila** [comment]
TBH, I'm having a look at your project, because I'm right in the middle of writing a parser for the new kicad_sch format which shares a lot with the kicad_pcb format. So in the end, I might produce a competitor (at least for git).

**Comment by Gasman2014** [comment]
I have used your schematic diff in the past - it was very helpful at spotting a design error. Thanks for that!

Schematic and layout diffs should live together in one tool with a unified interface, in my opinion.

What type of interface are you thinking about for the schematic diff? I rather regret the tK interface for KiDiff - the only reason I chose it was because tK is bundled with Python. And, as you can see, it looks dreadful :(
I believe that a better cross platform (and cross SCM) approach might be to use a web interface for the whole thing. I did recently mockup an initial layout. As you can see, my HTML design ideas aren't that good there either. I would love to see something like this directly accessible from the KiCad project manager window - I think there is a feature request for plugin access to the project manager. I wonder how you are planning to address this. 

Another design decision is whether you you plan to use a pre-rendered directory of artefacts or render them on demand like I have done with KiDiff. I do wonder if using git-hooks (or fossil-hooks :) )to generate the artefacts on each commit might be the easier and more flexible option. Using a browser based interface  would mean you would have to use javascript to manipulate the DOM but you could then compare arbitrary commits on the fly - for both schematic and pcb. This does require you to set up the project with this function from the start. (and you end up committing lots of output rendering which might go against the grain of SCM philosophy).

I think there does need to be more 'net awareness' so that entire nets can be highlighted. I know that @pointhi on the KiCad forum did some work on net diffs which recognised this but it doesn't seem to have progressed. https://forum.kicad.info/t/net-aware-pcb-diff-tool-kicad-python-demo/12270 .

I use Git for some of my work but I really like Fossil and think its a great fit for EDA projects. I think it is helpful not to constrain the use of an SCM to one particular program. I know Git is the main SCM in use but that doesn't mean it is the necessarily the best match for EDA work. FWIW, Fossil can import Git projects and is a single, cross-platform binary. `$fossil ui` will ping up a highly configurable interface with directly accessible diffs (like Git hub), bug logging, forum and a chat facility.  Worth a look - you don't get all that functionality with Git. Anyhow, I think it would be a mistake to force users to have to use one specific workflow if an alternative can easily be accommodated.

**Comment by jnavila** [comment]
> I have used your schematic diff in the past - it was very helpful at spotting a design error. Thanks for that!

It's always a pleasure to know that a tool has been useful.

> Schematic and layout diffs should live together in one tool with a unified interface, in my opinion.

Initially, I was less interested in a layout diff, because I never route my boards myself. A diff on Gerber file would be more useful to me. But, anyway a unified user interface available from your main tool would be better indeed.
> 
> What type of interface are you thinking about for the schematic diff? I rather regret the tK interface for KiDiff - the only reason I chose it was because tK is bundled with Python. And, as you can see, it looks dreadful :(
> I believe that a better cross platform (and cross SCM) approach might be to use a web interface for the whole thing. I did recently mockup an initial layout. As you can see, my HTML design ideas aren't that good there either. I would love to see something like this directly accessible from the KiCad project manager window - I think there is a feature request for plugin access to the project manager. I wonder how you are planning to address this.

Your idea of serving some data through HTTP is great. I would like to build something similar in order to serve versions of the design files on demand and allow to navigate history. I'd prefer to have a full blown single page application (lots of javascript which would process the design files) that would talk to a back-end server which would extract data from the SCM. This is a lot more evolved than serving almost static pages, but it adds a feeling of using a "real" application. For me, developing the kicad diff for sch was just an excuse for developing in a new language, so I would continue on this path and extend the application with the same language (agreed, not as accessible as Python). I haven't taken time until now to really start it though.

> 
> Another design decision is whether you you plan to use a pre-rendered directory of artefacts or render them on demand like I have done with KiDiff. I do wonder if using git-hooks (or fossil-hooks :) )to generate the artefacts on each commit might be the easier and more flexible option. Using a browser based interface would mean you would have to use javascript to manipulate the DOM but you could then compare arbitrary commits on the fly - for both schematic and pcb. This does require you to set up the project with this function from the start. (and you end up committing lots of output rendering which might go against the grain of SCM philosophy).

As I said, It would be better to not prerender anything, if the application can draw it directly from the SCM, without needing kicad itself. This last condition is a must to me, given how the bindings of Kicad are barely linkable with other modules of python.

> I think there does need to be more 'net awareness' so that entire nets can be highlighted. I know that @pointhi on the KiCad forum did some work on net diffs which recognised this but it doesn't seem to have progressed. https://forum.kicad.info/t/net-aware-pcb-diff-tool-kicad-python-demo/12270 .

That's a totally different model, and a more complex one. For now, plotgitsch only performs diffs on shapes, and does not "understand" schematics. Tha's yet another field of extension of the existing app.

> I use Git for some of my work but I really like Fossil and think its a great fit for EDA projects. I think it is helpful not to constrain the use of an SCM to one particular program. I know Git is the main SCM in use but that doesn't mean it is the necessarily the best match for EDA work. FWIW, Fossil can import Git projects and is a single, cross-platform binary. `$fossil ui` will ping up a highly configurable interface with directly accessible diffs (like Git hub), bug logging, forum and a chat facility. Worth a look - you don't get all that functionality with Git. Anyhow, I think it would be a mistake to force users to have to use one specific workflow if an alternative can easily be accommodated.

I implemented Git scm because I use only Git for all my new project, and because a native implementation is available in OCaml (the language I use). I don't think there is a binding with Fossil (which is quite neat, btw), but doing some commands much in the same way as Kicad-Diff does would be feasable. That's another direction of extension of the application.

**Comment by Gasman2014** [comment]
BTW, have you seen the AllSpice Altium schematic diff tool? The interface design looks quite a good starting point. http://www.allspice.io

**Pull request merged**
