### PR TITLE
Adds CLI super powers

### PR DESCRIPTION
**Pull request by leoheck**
Initial attempt to make this more user friendly.

### CODE REVIEW

**Comment by Gasman2014** [comment]
Thank you very much for your contribution - this helps tidy up some of the loose code. 
Thanks for catching the typos - although, on this side of the pond we still use 'colour' ;)

**Comment by sunwukonga** [comment]
Oops, I should have commented earlier.

There are a few problems with the commit.

The checks for commit1 and commit2 arguments should use: 
```python
if args.commit1 is None and args.commit2 is None:
```
as it is, it doesn't work.

It also currently stops the program from being able to use the gui to select the `kicad_pcb` file.

**Comment by sunwukonga** [comment]
I'll add add a PR to address this.

**Comment by leoheck** [comment]
@Gasman2014 sure! 

I can revert/fix that. Or change whatever is necessary to improve this with your thoughts. You don't need to close this PR. I checked the box enabling you to improve/fix things my own PR to make it easier. @sunwukonga 

Don't you like that kind of approach?

**Pull request merged**
