### PR TITLE
Improvements on triptych page

### PR DESCRIPTION
**Pull request by leoheck**
This PR 
- Organizes HTML assets to be more comprehensive
- Fixed pan and zoom on smaller images on triptych page
- Overall improvements on triptych page making it fit the screen

Extra work remaining from my last PR.
- Avoids duplicated work when plotting Kicad layers

### CODE REVIEW

**Comment by Gasman2014** [comment]
I have tried running your latest iteration.

I had some trouble with the newer env.sh which seems to want to add an 'ls -la' of my current directory to the path - which was not what I expected.

$echo $PATH
/Users/johnpateman/.opam/4.09.1/bin:/Users/johnpateman/Documents/Code/KiCad-Diff:…..
--—snip---

$ source ./env.sh

$ echo $PATH
/Users/johnpateman/.opam/4.09.1/bin:total 176 drwxr-xr-x@ 13 johnpateman staff 416B 31 Mar 22:06 ./ drwxr-xr-x@ 34 johnpateman staff 1.1K 31 Mar 22:06 ../ drwxr-xr-x@ 14 johnpateman staff 448B 31 Mar 23:18 .git/ -rw-r--r--@ 1 johnpateman staff 1.9K 31 Mar 22:06 README.md -rw-r--r-- 1 johnpateman staff 1.6K 31 Mar 22:06 blank.svg -rw-r--r-- 1 johnpateman staff 815B 31 Mar 22:06 env.sh -rwxr-xr-x 1 johnpateman staff 825B 31 Mar 22:06 git-imgdiff -rwxr-xr-x 1 johnpateman staff 179B 31 Mar 22:06 git-kdiff-log -rwxr-xr-x 1 johnpateman staff 20K 31 Mar 22:06 kdiff -rw-r--r-- 1 johnpateman staff 5.3K 31 Mar 22:06 kdiff.css -rw-r--r-- 1 johnpateman staff 20K 31 Mar 22:06 kdiff.js -rw-r--r--@ 1 johnpateman staff 19K 31 Mar 22:06 main.html drwxr-xr-x@ 4 johnpateman staff 128B 31 Mar 22:06 misc/

——snip—- !

The PCB diffs are working and I like the ability to scroll through the layers and the diffs. The schematic diffs are no longer working though - even on Firefox. There are sch1.svg and sch2.svgs created at the root of the project which are correct representations (so plotgitsch is working OK) but there is also a sch-diff.svg which is empty. The sch-diff.svg is also rotated (the schematic sheets are landscape but the diff sheet is portrait. In each of the directories, there is a sch svg file but they are all blank (and I know there are differences). These are also all in portrait format.

I might have some time in a few days to dig in more.


[https://www.dropbox.com/s/h8vgmlpmepvd9v9/Screenshot%202021-03-31%20at%2023.32.03.png?dl=0 <https://www.dropbox.com/s/h8vgmlpmepvd9v9/Screenshot%202021-03-31%20at%2023.32.03.png?dl=0>]

**Comment by leoheck** [comment]
This is enough for me. Thank you.

I will check why env.sh is not working. I changed it to be able to source
it from anywhere. It is working for me. I will check this on Mac.

To make the process easier. I am generating a empty svgs whenever kidiff
doesn't have an svg available from kidiff or plotgitsch. So the browser
will show an empty canvas instead of something wierd or an error.

I am using my own plotgitsch version. I changed the git-imgdiff script to
generate svgs for schematics even it they don't have any changes. Please
upgrade your plotgitsch with my latest version.

To validate you have the right version of the git-imgdiff in your path, run
this

cat $(witch git-imgdiff)

And look inside, I removed the "compare" command. It is mostly copying and
renaming input files.

Thank you again.

**Comment by leoheck** [comment]
I adjusted some minor things on kidiff, but env.sh was is working on my girl's mac. How you are executing env.sh?
It has to be 
`$> source env.sh`

**Comment by Gasman2014** [comment]
Will have another look at the env.sh sourcing - that was how I was testing it. I had already added the working KiCad-Diff checkout to my PATH in the .zshrc to save having to run it each time. I’ve switched from bash to zsh and had been hacking my .zshrc so there may be something there that is causing the odd behaviour.

One important thing I noted is that both the lower images in the ’triptych’ three pane display actually show the same version.

**Comment by leoheck** [comment]
Cool. I use zsh too. I use [Oh-My-Zsh](https://ohmyz.sh/) to potentialize it. Installation is pretty easy too.

> One important thing I noted is that both the lower images in the ’triptych’ three-pane display actually show the same version.
Oh, thanks. Fixed.

**Comment by leoheck** [comment]
The wrong image is fixed.

**Comment by leoheck** [comment]
Now it is right.
image

One thing I have noticed now. This "Text" tab has an extra column on the second line, Is this ok?

**Comment by Gasman2014** [comment]
The reason this is not working in Safari is tedious but the fix is trivial; the 'values' parameter needs to be on the same line as the first line of the matrix. Apparently, for it to work in IE, the whole matrix needs to be on one line. I'm not planning on supporting i.e.

So this DOESN'T Work in Safari
```
<filter id="f1">
    <feColorMatrix id="c1" type="matrix" values="
    1   0   0   0   0
    0   1   0   1   0
    0   0   1   1   0
    0   0   0   1   0 " />
</filter>
```

But this does ...

 ```
<filter id="f1">
    <feColorMatrix id="c1" type="matrix" 
    values="1   0   0   0   0
    0   1   0   1   0
    0   0   1   1   0
    0   0   0   1   0 " />
</filter>
```

**Comment by Gasman2014** [comment]
The extra box is a bug. There should probably be three columns in this layout i.e an additional 'Reference' column. Was the 'Rev1' text placed as a footprint? There are probably a few other errors in the parser too. I don't think I have handled the 'hide' attribute properly as I noticed I had a similar layout problem with one of my boards.

**Comment by leoheck** [comment]
So it means that the first value has to be close to the = sign. Let me fix this.

> Was the 'Rev1' text placed as a footprint? There are probably a few other errors in the parser too. I don't think I have handled the 'hide' attribute properly as I noticed I had a similar layout problem with one of my boards.

I am not sure if I got this question. So, you are saying this may be an issue on `kidiff`, right? Let's try to address this on the next PR then.

**Comment by Gasman2014** [comment]
I'm going to merge this BUT there is still a problem with Safari (there's a surprise!). The line break change you made in the `feColorMatrix` restores the diff functionality, BUT the changes to the `image-1-container `and` image-2-container `break the colour rendering in Safari. The bottom two images no longer have any colour. This does work OK in Firefox so I guess its yet another Safari quirk.

At the same time it would be worth incorporating the revision numbers in the two images. Perhaps reversed out text with the background the colour of the layer?

https://www.dropbox.com/s/2yk2kqv9tv047w8/Screenshot%202021-04-01%20at%2017.33.44.png?dl=0

**Comment by leoheck** [comment]
Oh, you already merged it. I could have done something about it. Didn't know this. Let me check what I can do about it. First of all, I will have to find a better way to validate these things on Safari.

**Pull request merged**
