### PR TITLE
Late fixes and README.md cleanup

### PR DESCRIPTION
**Pull request by leoheck**
README.md cleanup

- Old unnecessary instructions were removed
- Images sizes were improved
- Command help was updated
- Usage examples were added

### CODE REVIEW

**Comment by leoheck** [comment]
Yeah, it will be good to read the readme one more time, to check if all the info is usable. It is good to have something clean so others like me can see this, use it easily and help to improve it.

**Comment by leoheck** [comment]
Hey, @Gasman2014 I was able to sync this with your current master branch
It would be nice if you could check this and merge if possible. 

- It updates images on README.md so they will be more visible and organized. The original version didn't change the image sizes, and the previous and partial update (which is currently set) has all images super small. 
- It fixes the behavior for SVN
- It also improves Fossil commit messages that were being displayed with tabs, now it is easier to read.
- It improves the command line after launching the webserver, it is clean now. 

I've tested this with the SCMs I've created (Fossil, SVN and GIT) it seems to be working fine.

**Comment by leoheck** [comment]
Current terminal output if you are curious about it.
image

**Comment by Gasman2014** [comment]
Looks good (on limited testing). Thank you very much for your contribution.

**Pull request merged**
