### PR TITLE
Multiple fixes and enhancements

### PR DESCRIPTION
**Pull request by TheTrueTom**
First of all thanks for all your work. I believe this tool is pretty amazing and could be very useful.

I had a hard time making it work, but I'm no python expert.
Here is what I did and could figure out to make it work :

- Change some git to gitProg to get them to work as git location may vary
- Create a convertProg path as again location may vary depending on the way it was installed
- Add -channel RGB to convert -negate. Apparently needed for imagemagick latest version
- Change prj, layer = prjct.split('-') so it works for project containing a hyphen in their name
- Add a time.sleep(1) between svg creation and conversion as there seemed to be a race condition there.

Do not hesitate if you would like some details on some of those changes

### CODE REVIEW

**Comment by TheTrueTom** [comment]
Forgot to say that I had to add an explicit path for the .py file as well as for the grep command or it refused to work. Can't really say why it wouldn't find it

**Comment by Gasman2014** [comment]
Hi,
Excited to get my first ever pull request!
Thank you for your kind comments; I am not really any sort of programmer (i am actually a hospital doctor) - you have done well to make sense of my stylistically awful hacked together efforts. This is my first real program with Python.
I am presently investigating removing the rendering to bitmap stage which is very slow. I can produce svg files of each diff layer very simply and am investigating overlaying these and using the html 'filter' to build up a composite image.

**Comment by TheTrueTom** [comment]
Hi,
I'm not a professional coder either, just a chemist. I will be interested to follow on this project as soon as I have a little bit more time.

**Comment by Gasman2014** [comment]
You might be interested in my current iteration which is plotting .svgs directly and using feColorMatrix manipulations. It is virtually instantaneous and resolution independent.

**Pull request merged**
