### PR TITLE
Support for multiple Kicad projects (with GIT) and overall improvements

### PR DESCRIPTION
**Pull request by leoheck**
Hi John, 

I was trying to update this project considering to support for multiples Kicad repositories inside one repo as I reported some days ago here https://github.com/Gasman2014/KiCad-Diff/issues/19

Well, while I was doing this (which is already working) I've fixed/improved some other minor things in this project.

For instance, it has only one script to execute everywhere (Win/Linux/OsX) now, it will be easier to maintain. This includes plotPCB. The main script works with GUI and without GUI at the same time depending on how it is being launched so there is no need for kidffi_gui.py as well.

I've also
- added 2 extra layers on plotPCB. I have one board that have 6 layers
- started to move/think about removing the HTML stuff from the code (this is not done yet)
- improved a little bit the GUI window, so the `Cancel` buttons and the `Esc` key work to close the program.
- improved the command line, so it is cleaner now even when exiting from the program or the webserver

I would like to see if you are interested in these changes.
If yes, we can try to improve other SCMs (svn, fossil) if you think it is useful and also try to finish this HTML cleanup.

What do you think?

Ah, please, try it on your machine if you have time. (I want to see if it is still working on MacOSX, for instance)
Have a good day.

### CODE REVIEW

**Comment by leoheck** [comment]
Actually, I was able to remove the HTML/CSS from the code. The HTML can be improved, but right now it is better than it was.

**Comment by leoheck** [comment]
One giid thing to improve are these file paths, so they can be more generic to work on other systems. I am testing on linux.

**Comment by Gasman2014** [comment]
Hi Leandro

Thank you very much for these PRs. I have been a bit too busy recently to spend much time on this but am grateful for your interest.

I think the idea of the single script is excellent. This project was initially developed for a personal need and I have grafted bits on but have not been able to test it extensively on other platforms. Thank you for fixing this.

Extra layers - probably the best solution is to parse the .kicad_pcb file itself to determine the correct number of layers but this is a very useful addition. I had thought about some configurable preferences for colours but I am not sure it is necessary as they are easy enough to hack in the script. As you will see

Moving the HTML code outside the program - Yes, this was my next priority as the main script is exceptionally ugly and difficult to edit. Thank you!

The GUI window - this is my first TkInter program and I found it a bit of an uphill struggle. Glad you managed to fix it.

However, at present I am unable to run it as there are a couple of problems.

It runs if I use the CLI and define the SCM, even after moving  plotpcb to my $PATH (/usr/local/bin) but fails at the plotting stage

Generating images

Plot1 error: readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/plotPCB.py': [Errno 2] No such file or directory

but using the GUI It fails at around line 1200 - the scmAvailable() function returns a list of SCM programs that have been installed not the ones that are in operation on the repo.

I think you are  trying to get this function to do double duty - it is supposed to identify the SCM from the command line but also assumes that there is only one SCM available or applied to one directory.
I seem to recall i just put the choice of SCMs in my personal order of priority (Fossil/Git/SVN) as I use all three of them for different things. As it stands (and I have tried this in a couple of Git only repos), but I am getting the following error -

  File "kidiff", line 1233, in <module>
    print("Kicad Project:", kicad_project_path)
NameError: name 'kicad_project_path' is not defined

I determine which SCM is in use by the getSCM() function which does a brute force check on what is available  and in operation on any checkout.

I don’t have a great deal of time at the moment to dig into a solution for this but I am happy to test it further if you can fix it. Whatever solution you come up with it should be able to cope with multiple SCMs on the one machine and, ideally multiple SCMs in the same checkout. As I say, I have chosen an arbitrary order of priority - a better solution (if multiple SCMs apply to one repo) would be to allow the user to choose at the GUI stage (as you can with the CLI) - perhaps with a drop down?

I would be happy to merge any limited solution that fixes the GUI issue.

Many thanks and sorry I can’t dig in a bit more at the moment.

BW

John

**Comment by leoheck** [comment]
Hi John! We are all busy, it is not a problem at all but I really appreciate that you have tested it and also returned with the issues. This helps a lot. I will address these issues to make it working on your computer. I still want to think about how to improve it to make the system paths more generic.

**Comment by leoheck** [comment]
John, this last commit fixes the missing `readlink -f` on OSX that I use to find the script path. It should fix this, but I am not 100% sure since I could not test yet. I will try to find a mac to do it as soon as possible.

**Comment by leoheck** [comment]
Please, try using this command initially to skip the SCM question using the GUI
```kidiff -s git -v board.kicad_pcb```

**Comment by leoheck** [comment]
Now, it is a good time to try.
I've tried to fix the selection of the SCM in the GUI 
image

Also, the title here shows the SMC selected in the last window.
image

**Comment by Gasman2014** [comment]
I have tried this both as a CLI and the GUI.

On the CLI, I am not seeing any diffs generated and I am sure that there are differences.

```
python3 kidiff -s git -a 78949 -b aefc7 /Users/johnpateman/EDA_Workspace/Projects/Test_SCM_Projects/cadlab_test/TestGITKC2/ThermocoupleLogger.kicad_pcb

 Project PATH: /Users/johnpateman/EDA_Workspace/Projects/Test_SCM_Projects/cadlab_test/TestGITKC2
Kicad Project: .
   Board Name: ThermocoupleLogger.kicad_pcb

 Commit 1 (a): 78949
 Commit 2 (b): aefc7

There is no difference in .kicad_pcb file in selected commits
```

The GUI invocation brings up the SCM selection window, the file browser and the Tk window to select the diffs and then fails - are you setting the 'Kicad Project' correctly? 

```
Project PATH: /Users/johnpateman/EDA_Workspace/Projects/Test_SCM_Projects/trial_fsl
Kicad Project: ./
   Board Name: ThermocoupleLogger.kicad_pcb
Traceback (most recent call last):
  File "./kidiff", line 672, in <module>
    artifacts = fossil.get_artefacts(settings.escape_string(prjctPath), prjctName, kicad_project_path)
  File "/Users/johnpateman/Code/KiCad-Diff-Master/scms/fossil.py", line 139, in get_artefacts
    a, *tail = fArtifacts.split(' |')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by Gasman2014** [comment]
This path looks odd to me  - .//

Screen Shot 2020-09-30 at 21 01 02

**Comment by Gasman2014** [comment]
Hi Leo,

Sorry it has taken a while but I had a bit of time and wanted to get back to you. 

In principle, I am happy with most of the changes in this PR but I do have some issues which is why I have not merged it.  I am also struggling to get this to run in macOS so need to get to the bottom of that first. I can only get the Git version to run at all, the SVN version beachballs and doesn't display any versions. The'fossil' version fails thus;

```
 Project PATH: /Users/johnpateman/EDA_Workspace/Projects/Test_SCM_Projects/trial_fsl
Kicad Project: ./
   Board Name: ThermocoupleLogger.kicad_pcb
Traceback (most recent call last):
  File "/Users/johnpateman/Downloads/KiCad-Diff-master-2/kidiff", line 660, in <module>
    artifacts = fossil.get_artefacts(settings.escape_string(prjctPath), prjctName, kicad_project_path)
  File "/Users/johnpateman/Downloads/KiCad-Diff-master-2/scms/fossil.py", line 139, in get_artefacts
    a, *tail = fArtifacts.split(' |')
AttributeError: 'list' object has no attribute 'split'
```
I am glad that you split off the templating code - this was beginning to annoy me and it is a sensible plan to move the SCMS into separate files. Obviously happy for extra layers to be supported and the edits to the documentation.

I am also pleased that you are able to develop this to use this with multiple KiCad projects.

One issue I don't particularly like is the need to select the SCM in the GUI ahead of opening the .kicad_pcb from a checkout.
I would prefer for this to be autodetected and only present a dialogue for disambiguation if there is more than one SCM in play. 

As thing stand, I am only able to run the Git version and that fails to detect any differences between two boards where I know there have been changes.

**Comment by leoheck** [comment]
Hi @Gasman2014 I also had other priorities to attend.

Thanks for the feedback,

I think I have access to one Macbook to address your usability issues on Mac

> One issue I don't particularly like is the need to select the SCM in the GUI ahead of opening the .kicad_pcb from a checkout.
I agree. That makes sense, I mostly prefer to use it on CLI and I was using the SCM flag to pre-select it. Now I know your intent, I will try to address this too.

**Comment by kylenahas** [comment]
Anything I can help do to bring this PR to the finish line? I have access to a Mac and Tkinter experience.

**Comment by leoheck** [comment]
If you know how to fix this the author has requested I will love to have
this help. The issue is that I could not work on it yet. I am having
vacation on 27th/Jan, and then I think I will have more free time. But any
help with is welcome if you know how to do it before I could have this free
time.

**Comment by Gasman2014** [comment]
I would be delighted if anyone could help to push this over the line. In principle, I am generally happy with what @leoheck has proposed. I am particularly pleased that it has been split into more manageable modules - splitting the SCM & templating code off. Personally I use separate Fossil repos for my projects and avoid nesting repos so I don't have a test case for the multiple repos setup but happy if someone else can test it as long as it doesn't break current functions.

However, I have not been able to merge this as it breaks functionality on my macOS setup. Other issues are that it appears to only function with git checkouts (and even then it didn't seem to identify differences when I used a test cases with known differences.) It no longer seems to work with SVN or Fossil checkouts.

I would rather **not** have to preselect the SCM before opening the repo. In current master, the type of SCM is inferred from the checkout. Arbitrarily, I have chosen to identify the SCMs in my personal preferred order but, more reasonably,, I would be happy for a warning disambiguation dialogue to pop up if more than one SCM available OR to use a select button in the main GUI dialogue.

Any Tk improvements would be gratefully received. Also, and improvements in the HTML would be very welcome.

**Comment by leoheck** [comment]
Hi. Today I am free. I will be reading this to check what has to be done for us to approve this. Lets see what I can do.

**Comment by leoheck** [comment]
I am super curious why you need Fossil and SVN these are pretty old stuff. =/

**Comment by leoheck** [comment]
Hey @Gasman2014 please, try to find an SVN and Fossil project to share with me to test this.
I think svn project is not that easy to create and I don't know how to use fossil.

**Comment by Gasman2014** [comment]
Have you tried out Fossil recently? Its now on 2.14 and is under active development. Have a look at the Fossil SCM website. Fossil is a single, cross platform application written by Richard Hipp - the inventor of SQLite. In many ways it is ideal for managing an electronic project. Fossil has an in built web server (just type 'fossil ui’ on the command line). Fossil has an in built wiki & technotes which are great for documenting a project. There is a customisable bug tracker, forum and now even a chat client built in. No dependencies and all in a 3MB executable. Whats not to like! The whole Fossil website is actually a running instance of Fossil. Its my favourite SCM and is really worth checking out.  https://fossil-scm.org <https://fossil-scm.org/> . I have been looking at the feasibility of trying to incorporate this cho45/kicad-utils: KiCAD library / schematic / pcb ... - GitHubgithub.com › cho45 › kicad-utils <https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiQm9Sj3LzuAhUmQ0EAHfyTBuUQFjACegQIBBAC&url=https%3A%2F%2Fgithub.com%2Fcho45%2Fkicad-utils&usg=AOvVaw0lSSiQhw20-2i3reg7LD1H> as a  viewer for KiCad schematics and layouts within Fossil.

I have my libraries in SVN. I quite like this for shared resources as you get a lock on the checkout so avoid merge conflicts (which are painful when you use an SCM for EDA. Its not like a code conflict where you can work out the intent of the change).

BW

John

**Comment by Gasman2014** [comment]
OK - will post when I get home Im just going to my car.

BW

John

**Comment by Gasman2014** [comment]
Quickest way to get started with a Fossil project is to simply import from a git project. See below.

Will have a look at how to get an SVN to you.
John



Git → Fossil

To import a Git repository into Fossil, run commands like this:

cd git-repo
git fast-export --all | fossil import --git new-repo.fossil
In other words, simply pipe the output of the "git fast-export" command into the "fossil import --git" command. The 3rd argument to the "fossil import" command is the name of a new Fossil repository that is created to hold the Git content.

The --git option is not actually required. The git-fast-export file format is currently the only VCS interchange format that Fossil understands. But future versions of Fossil might be enhanced to understand other VCS interchange formats, and so for compatibility, use of the --git option is recommended.



John Pateman

**Comment by Gasman2014** [comment]
Hi Leandro,

This is the easiest way I have found of serving SVN repos on macOS: https://langui.net/simple-svn-server/ <https://langui.net/simple-svn-server/>
Not perfect but very simple and fine for testing.

I have attached a zipped repo of an old project - its a bit messy, sorry! Think it is OK for testing purposes. Generally I use Fossil (and sometimes Git) for my projects and only use SVN for libraries. 

Fossil commands are very similar to Git. ‘fossil open’, ‘fossil timeline’, ‘fossil addremove (files)’, ‘fossil checkout xxx’ and ‘fossil commit’ will get you there. ‘Fossil ui’ will bring up a web interface to the entire project. And ‘fossil help’ :)


BW

John

**Comment by leoheck** [comment]
The initial test with fossil seems to be working.

> I have attached a zipped repo of an old project 

@Gasman2014 where the attachment is?
I am seeing this on the GitHub page and on the email thread. But here I cannot see any attachment.
Can you point me to where I can get this?

**Comment by leoheck** [comment]
So, I created a git repo, with a kicad project. There will be one commit adding files.
Then I tried the following command, but I don't see a list of commits.
```
git fast-export --all | fossil import --git new-repo.fossil
```

I am using these commands, but they don't show any changes
```
fossil changes
fossil timeline
```

What am I doing wrong?

**Comment by Gasman2014** [comment]
I've had a quick look at this but have run into a problem. Fossil.py, ln 62

```
    dateTime, _ = settings.run_cmd(info1).strip()
NameError: name 'info1' is not defined
```
 But I think you mean 
```
    dateTime,_=settings.run_cmd(fossilInfo1)
```
There is a similar error on ln 67

After that, I get here;

```
Generating images

Plot1 error: Traceback (most recent call last):
  File "/usr/local/bin/plotpcb", line 74, in <module>
    processBoard(boardName, plotDir)
  File "/usr/local/bin/plotpcb", line 16, in processBoard
    board = pcbnew.LoadBoard(boardName)
  File "/Applications/Kicad/kicad.app/Contents/Frameworks/python/site-packages/pcbnew.py", line 6888, in LoadBoard
    return _pcbnew.LoadBoard(*args)
IOError: Unable to open filename "/Users/johnpateman/EDA_Workspace/Projects/JW_Avalanche//kidiff/./7facf2/Avalanche.kicad_pcb" for reading
```
 The '.' in the path is wrong. The kidiff/7facf2 directory exists, but it is empty.
 ```
$ls -la  /Users/johnpateman/EDA_Workspace/Projects/JW_Avalanche/kidiff
total 16
drwxr-xr-x   8 johnpateman  staff   256B  3 Feb 14:03 ./
drwxr-xr-x@ 39 johnpateman  staff   1.2K  3 Feb 12:53 ../
-rw-r--r--@  1 johnpateman  staff   6.0K  3 Feb 14:03 .DS_Store
drwxr-xr-x   2 johnpateman  staff    64B  3 Feb 13:59 52a9e6/
drwxr-xr-x   2 johnpateman  staff    64B  3 Feb 12:53 601be1/
drwxr-xr-x   2 johnpateman  staff    64B  3 Feb 12:56 71af58/
drwxr-xr-x   2 johnpateman  staff    64B  3 Feb 12:53 7facf2/
drwxr-xr-x   2 johnpateman  staff    64B  3 Feb 14:02 bd8978/
```

**Comment by leoheck** [comment]
True, my bad, I fixed this now.

I was just creating my initial fossil repo. I just have the initial commit, now I have to add changes in the board to be able to be compared by Kidif.

Could you update your files to test one more time?

**Comment by leoheck** [comment]
Oh wait, it still has the issue. I now have a fossil repo with a board that has changes

**Comment by leoheck** [comment]
Ok, that issue was fixed. You may test now.

It was able to do the job. Maybe we are going to see other issues, I will have to use it more.
image

Inside of the kidiff script I saw this, this is the current order I am accepting, is this the way you prefer @Gasman2014 ?
```Current order of priority: Git > Fossil > SVN```

**Comment by Gasman2014** [comment]
OK, now hitting this.

```Plot1 error: readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
python3: can't open file '/plotPCB.py': [Errno 2] No such file or directory```

I have run the env.sh first and also tried copying both plotpcb and plotPCB.py elsewhere into my path (/usr/local/bin)

**Comment by Gasman2014** [comment]
With respect tot he order of the SCMs, I (reluctantly!) accept that Git probably has more users than Fossil and SVN is a lowly third so happy with that order.
What do you make of Fossil? I think it is a vey good fit for EDA projects. If you are interested I have some equivalent functionality to 'git smudge' which you might find interesting.
Anyhow, feel this is getting closer.

**Comment by leoheck** [comment]
Oh, I didn't check this plotPCB.py for mac. Let me check this too. I will have to set up a mac then it will take some time.
I am also trying to improve SVN now since I was able to create a sample project here.

For the order of scms, it doesn't matter, since the user can force from the command line with the flag --scm 
I prefer to use the order you think is better. And this won't be an issue since I think just a few people use multiple scms in the same project.

**Comment by Gasman2014** [comment]
There is a problem with the path emitted by 'plotpcb'. $SCRIPTPATH and $SCRIPT are empty.

This fixes it.

```
#!/bin/bash

# Wrapper for the plotPCB.py script
# It should work on Linux, Mac and possibly on Windows

readlink_osx()
{
	TARGET=$1
	echo $1

	cd $(dirname "$TARGET")
	TARGET=$(basename "$TARGET")

	# Iterate down a (possible) chain of symlinks
	while [ -L "$TARGET" ]
	do
	    TARGET=$(readlink "$TARGET")
	    cd $(dirname "$TARGET")
	    TARGET=$(basename "$TARGET")
	done

	# Compute the canonicalized name by finding the physical path 
	# for the directory we're in and appending the target file.
	DIR=$(pwd -P)
	RESULT="$DIR/$TARGET"
}

if [[ "$OSTYPE" == "darwin"* ]]; then
	SCRIPT=$(readlink_osx $0)
	SCRIPTPATH=$(dirname $SCRIPT)
	/Applications/Kicad/kicad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python ${SCRIPTPATH}/plotPCB.py $*
else
	SCRIPT=$(readlink -f $0)
	SCRIPTPATH=$(dirname $SCRIPT)
	/usr/bin/env python3 ${SCRIPTPATH}/plotPCB.py $*
fi
```

**Comment by leoheck** [comment]
I found the issue with the plotpcb. Fixed it, could not test it since I am still downloading kicad on my machine.
Can you check again if the plotpcb works?

**Comment by leoheck** [comment]
Oh, you fixed it too.

**Comment by Gasman2014** [comment]
Yay!! That is all working now and looks good. Thanks for all your input. All looking a lot better organised and hopefully meets your original target of multiple git repos. Many thanks. Will merge.

**Comment by leoheck** [comment]
Yay!! You can merge it. I will continue testing this. If I see issues I will fix.
I also want to split the html code on its own files. Lets see if I can do it.

**Comment by leoheck** [comment]
I am also working to make the SVN working, it is not good yet. If you can wait a little bit, let say until the end of the day or tomorrow it will be better.

**Comment by Gasman2014** [comment]
Closed via [b1653f9]

**Comment by Gasman2014** [comment]
I’ll hold off committing anything further until tomorrow. My master branch is currently working for fossil. Not sure if it right with git though - I had a problem with a git archive that I tried. Will look again tomorrow. 

John Pateman

**Pull request closed without merging**
